Add support for typed and scoped enums
cuberite/toluapp pull request #3
Opened 2017-06-20 20:51 UTC by peterbell10

Say I have in the c++ side:
```
enum class EffectID : Int32
{
    SFX_MOB_GHAST_WARN
};
```

This will be usable in lua as `EffectID.SFX_MOB_GHAST_WARN`.

2017-06-21 05:08 UTC, madmaxoft commented
Make sure that this doesn't lose any of our current API. Compile Cuberite without these changes, run it and issue the `api` command (from the APIDump built-in plugin); make a backup of the `Server/Cuberite_api.lua` file generated by this, and then repeat with these changes. Compare the two API files to see if anything changed.

2017-06-21 05:20 UTC, Seadragon91 commented
I tested this changes by comparing the generated Bindings.cpp. The only difference is the line with the time stamp. Is that enough as check?

2017-06-21 05:34 UTC, madmaxoft commented
Yes, that's a good enough check.

2017-06-21 05:34 UTC, madmaxoft commented
I'm not too sure about the types with names. What is that for?

2017-06-21 09:17 UTC, peterbell10 commented
@madmaxoft 
Sorry but I'm not sure what you mean by "types with names".

2017-06-21 09:33 UTC, madmaxoft commented
Sorry, I meant types with spaces.

2017-06-21 09:34 UTC, peterbell10 commented
Oh that's simple enough, it just means you can write
```
enum Foo : unsigned char {};
```

2017-06-21 10:19 UTC, madmaxoft commented
Oh, so it's only parser-side, not in the runtime.

2017-06-21 10:20 UTC, madmaxoft requested changes

2017-06-21 10:20 UTC, madmaxoft commented on src/bin/lua/scopedenum.lua
> +-- enhancements, or modifications.
I think it's safe to say that this copyright is not what you meant, unless you are secretly Waldemar :)

2017-06-21 10:43 UTC, peterbell10 commented on src/bin/lua/scopedenum.lua
> +-- enhancements, or modifications.
Well it was all just copied from `enumerate.lua` with some minor tweaks.  I haven't looked at the license though.

2017-06-23 11:48 UTC, peterbell10 commented on src/bin/lua/scopedenum.lua
> +-- enhancements, or modifications.
Is the way it is now OK? If not I might need a bit of help for what to put.

2017-06-23 11:50 UTC, madmaxoft approved these changes
Good enough for me.

2017-06-28 14:29 UTC, peterbell10 commented
Is there anything stopping this from getting merged?

2017-06-28 14:34 UTC, merged

2017-06-28 14:36 UTC, Seadragon91 commented
Ah should have don squash and rebase...

2017-06-30 08:50 UTC, madmaxoft commented
Is there any reason why the ScopedEnum is created anew, instead of putting it inside the regular Enum?

I'm trying to fix in-class enum handling and now there's duplicate code.

2017-06-30 12:34 UTC, peterbell10 commented
The main differences are the extra namespace qualifier to access the enum, and in `classScopedEnum:register` where there is an extra module output and the strong typing means the need for extra `static_cast`s.  I suppose it could be rewritten so `ScopedEnum` is just a container for `Enumerate` and move the `static_cast`s into `Enumerate:register`.

Though I don't think it's related to where the enum is declared; could you explain the issue with in-class enums?

2017-06-30 12:37 UTC, madmaxoft commented
I guess I'll rewrite it like that.

The problem with in-class enums is when two classes each have an enum with the same name:
```cpp
class cClassA
{
  enum eType { ... };
};

class cClassB
{
  enum eType { ... };
},
```
The parser doesn't use fully-qualified type names for *some* parts and ends up generating invalid code or mixing up the values.

2017-07-02 07:13 UTC, Seadragon91 commented
@peterbell10 If you look into the generated `Bindings.cpp` for eMaterial. That's the enum for the boat materials and they can be accessed over the class name, e.g. `cBoat.btOak`. The problem is now that the enum range check is not generated correctly, it's missing the class name.